remote_theme: mmistakes/minimal-mistakes@4.24.0

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single      
  - scope:
      path: ""
      type: home
      share: true
    values:
      layout: single
  - scope:
      path: ""
      type: auto
    values:
      layout: single
  - scope:
      path: "outdoor"
      type: home-outdoor
    values:
      layout: single
  - scope:
      path: "outdoor/backyard"
      type: home-outdoor-backyard
    values:
      layout: single


collections:
  home:
    output: true
    # exterior:
    #   output: true
    # outdoor:
    #   output: true
    #   backyard:
    #     output: true
  auto:
    output: true

include:
  - _pages

#inimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-CA"
timezone                 : "America/Toronto"
title                    : "Simple, Useful, Nifty DIY"
title_separator          : "-"
subtitle                 : ""
name                     : "Simple, Useful, Nifty DIY"
description              : "DIY"
url                      : "https://sundiy.ca"
baseurl                  : "/"
repository               : "sundiy-ca/sundiy-ca.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true #, false (default)
search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :
# cflr_analytics_url       : "https://a.opendoghuman.com"


# Social Sharing
twitter:
  username               : sundiy_ca
# facebook:
#   username               : opendoghuman
#   app_id                 :
#   publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Your Name"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
# footer:
#   links:
#     - label: "Mastodon"
#       icon: "fab fa-fw fa-mastodon"
#       url: https://mastodon.social/@opendoghuman
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: https://twitter.com/opendoghuman
#     - label: "Bluesky"
#       icon: "fab fa-fw fa-bluesky"
#       url: https://bsky.app/profile/opendoghuman.bsky.social
#     - label: "Reddit"
#       icon: "fab fa-fw fa-reddit-square"
#       url: https://www.reddit.com/r/opendoghuman/
#     # - label: "Facebook"
#     #   icon: "fab fa-fw fa-facebook-square"
#     #   url: 
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: https://github.com/opendoghuman/opendoghuman.github.io



# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

